REM || USEFUL INFORMATION:
REM || * = wildcard, match any or none. DO NOT USE ? IT BREAKS
REM || /S = recursive. use to delete from subfolders BE CAREFUL W/THIS
REM || /Q = quiet mode. if echo is off you don't need this but
REM || add it to RD commands just to be safe
REM ||
REM || START DELETIONS
REM ||

CD base

REM || Music deletions
CD sounds/music
DEL "[AA] Blissful People.opus"
DEL "[AA] Classroom Trial.opus"
DEL "[AA] Confess The Truth.opus"
DEL "[AA] Damon Gant - Swimming, Anyone.opus"
DEL "[AA] Detention Center.opus"
DEL "[AA] Dick Gumshoe - It's Detective Gumshoe!.opus"
DEL "[AA] Ema Skye - Turnabout Sisters.opus"
DEL "[AA] Ending.opus"
DEL "[AA] Investigation (Core).opus"
DEL "[AA] Investigation (Opening).opus"
DEL "[AA] Jake Marshall - Detective From the Wild West.opus"
DEL "[AA] Logic and Tricks.opus"
DEL "[AA] Marvin Grossberg - Age, Regret, Retribution.opus"
DEL "[AA] Maya Fey - Turnabout Sisters.opus"
DEL "[AA] Maya's Grief.opus"
DEL "[AA] Mia Fey - Turnabout Sisters (Ballad).opus"
DEL "[AA] Objection!.opus"
DEL "[AA] Prelude.opus"
DEL "[AA] Pursuit (Variation).opus"
DEL "[AA] Pursuit.opus"
DEL "[AA] Questioning (Moderato).opus"
DEL "[AA] Questioning (Allegro).opus"
DEL "[AA] Suspense.opus"
DEL "[AA] The DL-6 Incident.opus"
DEL "[AA] The SL-9 Incident.opus"
DEL "[AA] The Steel Samurai - Warrior of Neo Olde Tokyo.opus"
DEL "[AA] Trial.opus"
DEL "[AA] Victory!.opus"
DEL "[JFA] Berry Big Circus.opus"
DEL "[JFA] Confess The Truth.opus"
DEL "[JFA] Detention Center.opus"
DEL "[JFA] Ending.opus"
DEL "[JFA] Franziska von Karma - Great Revival.opus"
DEL "[JFA] Hotline of Fate.opus"
DEL "[JFA] Investigation (Core).opus"
DEL "[JFA] Investigation (Middle).opus"
DEL "[JFA] Investigation (Opening).opus"
DEL "[JFA] Kurain Village.opus"
DEL "[JFA] Maximillion Galactica - Fabulous!.opus"
DEL "[JFA] Maya Fey - Turnabout Sisters.opus"
DEL "[JFA] Miles Edgeworth - Great Revival.opus"
DEL "[JFA] More Blissful People.opus"
DEL "[JFA] Objection!.opus"
DEL "[JFA] Pearl Fey - Together with Pearly.opus"
DEL "[JFA] Prelude.opus"
DEL "[JFA] Psyche Locks.opus"
DEL "[JFA] Pursuit (Variation).opus"
DEL "[JFA] Pursuit.opus"
DEL "[JFA] Questioning (Allegro).opus"
DEL "[JFA] Questioning (Moderato).opus"
DEL "[JFA] Ringtone - Phoenix.opus"
DEL "[JFA] Ringtone - Toccata and Fugue.opus"
DEL "[JFA] Scars Carved by Fire.opus"
DEL "[JFA] Shelly de Killer - The Whim of a Murderous Gentleman.opus"
DEL "[JFA] The Steel Samurai's Ballad.opus"
DEL "[JFA] Toccata and Fugue.opus"
DEL "[JFA] Trial.opus"
DEL "[JFA] Tricks and Magic.opus"
DEL "[JFA] True Pain.opus"
DEL "[JFA] Victory!.opus"
DEL "[T&T] Confess The Truth.opus"
DEL "[T&T] Dahlia Hawthorne - Distant Traces of Beauty.opus"
DEL "[T&T] Detention Center.opus"
DEL "[T&T] Ending.opus"
DEL "[T&T] Godot - The Fragrance of Dark Coffee.opus"
DEL "[T&T] Furio Tigre - Swingin' Tiger.opus"
DEL "[T&T] Investigation (Core).opus"
DEL "[T&T] Investigation (Opening).opus"
DEL "[T&T] Larry Butz - When Something Smells, It's Usually Me.opus"
DEL "[T&T] Lordly Tailor.opus"
DEL "[T&T] Luke Atmey - I Just Want Love.opus"
DEL "[T&T] Mask DeMasque - Pleeeeease Listen.opus"
DEL "[T&T] Objection!.opus"
DEL "[T&T] Prelude.opus"
DEL "[T&T] Pursuit - Cornered (Variation).opus"
DEL "[T&T] Pursuit - Cornered.opus"
DEL "[T&T] Pursuit (Variation).opus"
DEL "[T&T] Pursuit.opus"
DEL "[T&T] Questioning (Allegro).opus"
DEL "[T&T] Questioning (Moderato).opus"
DEL "[T&T] Ringtone - Godot.opus"
DEL "[T&T] The Bitter Taste of Truth.opus"
DEL "[T&T] Tres Bien.opus"
DEL "[T&T] Trial.opus"
DEL "[T&T] Victor Kudo - How Sad, the Melody of this War Song.opus"
DEL "[T&T] Victory!.opus"
DEL "[DD] Apollo Justice - I'm Fine!.opus"
DEL "[DD] Athena Cykes - Let's Do This!.opus"
DEL "[DD] Bobby Fulbright - In Justice We Trust!.opus"
DEL "[DD] Boisterous People.opus"
DEL "[DD] Confess The Truth.opus"
DEL "[DD] Detention Center.opus"
DEL "[DD] Difficult People.opus"
DEL "[DD] Ending.opus"
DEL "[DD] Illegality of Fate.opus"
DEL "[DD] Investigation (Core).opus"
DEL "[DD] Investigation (Opening).opus"
DEL "[DD] Logic Trinity.ogg"
DEL "[DD] Miles Edgeworth - Great Revival.opus"
DEL "[DD] Objection! (Apollo).opus"
DEL "[DD] Objection! (Athena).opus"
DEL "[DD] Objection! (Phoenix).opus"
DEL "[DD] Pearl Fey - Together with Pearly.opus"
DEL "[DD] Pursuit (Variation).opus"
DEL "[DD] Pursuit.opus"
DEL "[DD] Questioning (Allegro).opus"
DEL "[DD] Questioning (Moderato).opus"
DEL "[DD] Simon Blackquill - Distorted Swordsmanship.opus"
DEL "[DD] Suspense.opus"
DEL "[DD] Suspicious People.opus"
DEL "[DD] Trial (Variation).opus"
DEL "[DD] Trial.opus"
DEL "[DD] Trucy Wright - Child of Magic.opus"
DEL "[DD] Victory!.opus"